routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::resource('bins','BinController');
Route::resource('category','CategoryController');
Route::resource('unit','UnitController');
Route::resource('product','ProductController');
Route::resource('customer','CustomerController');
Route::resource('warehouse','WarehouseController');
Route::resource('role','RoleController');
Route::resource('user','UsersController');
Route::resource('report','ReportController');
Route::resource('report','UserrportController');


Route::get('dashboard', function () {
        return view('/dashboard');
    });

    Route::get('userreport', function () {
        return view('/userreport');
    });

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    public $table="products";
    protected $fillable=['product_name','product_code','category','unit','bin','description'];
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;
use App\Product;
use App\Unit;
use App\Category;
use App\Bin;
use Illuminate\Http\Request;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $product = Product::latest()->paginate(5);
        return view('product.index',compact('product'))
            ->with('i', (request()->input('page', 1) - 1) * 5);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $unit = Unit::all();
        $category = Category::all();
        $bin = Bin::all();
        return view('product.create',compact('unit','category','bin'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'product_name' => 'required',
            'product_code' => 'required',
            'category' => 'required',
            'unit' => 'required',
            'bin' => 'required',
            'description' => 'required',
        ]);
        Product::create($request->all());
        return redirect()->route('product.index')
                        ->with('success','product created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function show(Product $product)
    {
        return view('product.show',compact('product'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function edit(Product $product)
    {
        return view('product.edit',compact('product'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Product $product)
    {
        $request->validate([
            'product_name' => 'required',
            'product_code' => 'required',
            'category' => 'required',
            'unit' => 'required',
            'bin' => 'required',
            'description' => 'required',
        ]);
  
        $product->update($request->all());
  
        return redirect()->route('product.index')
                        ->with('success','Unit updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function destroy(Product $product)
    {
        $product->delete();
  
        return redirect()->route('product.index')
                        ->with('success','Unit deleted successfully');
    }
}

resources/views/product/create.blade.php
@extends('layouts.master')
  
@section('content')

<div id="content" class="app-content" role="main">
  	<div class="app-content-body ">
	    

        <div class="bg-light lter b-b wrapper-md">
            <h1 class="m-n font-thin h3">Add Product</h1>
        </div>

        <div class="wrapper-md">
            <div class="panel panel-default">
                <div class="panel-heading btnbck">
                    <a class="btn btn-success" href="{{ route('product.index') }}"> Back</a>
                </div>

                <div class="table-responsive">
					<div class="container"> 

                    @if ($errors->any())
    <div class="alert alert-danger">
        <strong>Whoops!</strong> There were some problems with your input.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
   
<form action="{{ route('product.store') }}" method="POST">
    @csrf
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Product Name:</strong>
                <input type="text" name="product_name" class="form-control" placeholder="Product Name">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Product Code:</strong>
                <input type="text" name="product_code" class="form-control" placeholder="Product Code">
            </div>
        </div>

        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Category:</strong>
                <select name="category" class="form-control">
                        <option value="">--Select--</option>
                    @foreach ($category as $item)
                        <option value="{{$item->name}}">{{$item->name}}</option>
                    @endforeach
                </select>
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Unit:</strong>
                <select name="unit" class="form-control">
                        <option value="">--Select--</option>
                        @foreach ($unit as $item)
                            <option value="{{$item->name}}">{{$item->name}}</option>
                        @endforeach
                </select>
                
                
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Bin:</strong>
                <select name="bin" class="form-control">
                        <option value="">--Select--</option>
                        @foreach ($bin as $item)
<option value="{{$item->name}}">{{$item->name}}</option>
@endforeach
                </select>
                
               
            </div>
        </div>

        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Description:</strong>
                <textarea class="form-control" style="height:150px" name="description" placeholder="Description"></textarea>
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 text-center btnsubmitpad">
                <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </div>
   
</form> 

					</div>
                </div>
            </div>
        </div>
	</div>
</div>


@endsection

resources/views/product/edit.blade.php
@extends('layouts.master')
   
@section('content')

<div id="content" class="app-content" role="main">
  	<div class="app-content-body ">
	    

        <div class="bg-light lter b-b wrapper-md">
            <h1 class="m-n font-thin h3">Edit Product</h1>
        </div>

        <div class="wrapper-md">
            <div class="panel panel-default">
                <div class="panel-heading btnbck">
                    <a class="btn btn-success" href="{{ route('product.index') }}"> Back</a>
                </div>

                <div class="table-responsive">
					<div class="container">
					
					@if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
  
    <form action="{{ route('product.update',$product->id) }}" method="POST">
        @csrf
        @method('PUT')
   
         <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Product Name:</strong>
                    <input type="text" name="product_name" value="{{ $product->product_name }}" class="form-control" placeholder="Name">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Product Code:</strong>
                        <input type="text" name="product_code" value="{{ $product->product_code }}" class="form-control" placeholder="Name">
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="form-group">
                            <strong>Category:</strong>
                            <input type="text" name="category" value="{{ $product->category }}" class="form-control" placeholder="Name">
                        </div>
                    </div>

                    <div class="col-xs-12 col-sm-12 col-md-12">
                            <div class="form-group">
                                <strong>Bin:</strong>
                                <input type="text" name="bin" value="{{ $product->bin }}" class="form-control" placeholder="Name">
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-12 col-md-12">
                                <div class="form-group">
                                    <strong>Bin:</strong>
                                    <input type="text" name="unit" value="{{ $product->unit }}" class="form-control" placeholder="Name">
                                </div>
                            </div>
                    
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Detail:</strong>
                    <textarea class="form-control" style="height:150px" name="description" placeholder="Detail">{{ $product->description }}</textarea>
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12 text-center btnsubmitpad">
              <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>
   
    </form>
					
					</div>
                </div>
            </div>
        </div>
	</div>
</div>


@endsection

resources/views/product/index.blade.php
@extends('layouts.master')
 
@section('content')

<div id="content" class="app-content" role="main">
  	<div class="app-content-body ">
	    

        <div class="bg-light lter b-b wrapper-md">
            <h1 class="m-n font-thin h3">List Product</h1>
        </div>

        <div class="wrapper-md">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <a class="btn btn-success" href="{{ route('product.create') }}"> Add Product</a>
                </div>
                @if ($message = Session::get('success'))
    <div class="alert alert-success">
        <p>{{ $message }}</p>
    </div>
@endif
                <div class="table-responsive">
                <table ui-jq="dataTable" id="example" ui-options="{
                    sAjaxSource: 'api/datatable.json',
                    aoColumns: [
                        { mData: 'engine' },
                        { mData: 'browser' },
                        { mData: 'platform' },
                        { mData: 'version' },
                        { mData: 'grade' }
                    ]
                    }" class="table table-striped table-bordered b-t b-b">

                        @if ($message = Session::get('success'))
                            <div class="alert alert-success">
                                <p>{{ $message }}</p>
                            </div>
                        @endif
    
                        <div class="container">
                            <thead>
                                <tr>
                                    <th>No</th>
                                    <th>Product Name</th>
                                    <th>Product code</th>
                                    <th>Category</th>
                                    <th>Bin</th>
                                    <th>Unit</th>
                                    <th>Description</th>
                                    <th width="280px">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($product as $value)
                                <tr>
                                    <td>{{ ++$i }}</td>
                                    <td>{{ $value->product_name }}</td>
                                    <td>{{ $value->product_code }}</td>
                                    <td>{{ $value->category }}</td>
                                    <td>{{ $value->unit }}</td>
                                    <td>{{ $value->bin }}</td>
                                    <td>{{ $value->description }}</td>
                                    <td>
                                        <form action="{{ route('product.destroy', $value->id) }}" method="POST">
                        
                                            <a class="btn btn-info" href="{{ route('product.show',$value->id) }}">Show</a>
                            
                                            <a class="btn btn-primary" href="{{ route('product.edit',$value->id) }}">Edit</a>
                        
                                            @csrf
                                            @method('DELETE')
                            
                                            <button type="submit" class="btn btn-danger">Delete</button>
                                        </form>
                                    </td>
                                </tr>
                                @endforeach
                            <tbody>
                        </div>
                      

                </table>
                </div>
            </div>
        </div>
	</div>
</div>


@endsection

resources/views/product/show.blade.php
@extends('layouts.master')
@section('content')

<div id="content" class="app-content" role="main">
  	<div class="app-content-body ">
	    

        <div class="bg-light lter b-b wrapper-md">
            <h1 class="m-n font-thin h3">Show Product</h1>
        </div>

        <div class="wrapper-md">
            <div class="panel panel-default">
                <div class="panel-heading btnbck">
                    <a class="btn btn-success" href="{{ route('product.index') }}"> Back</a>
                </div>

                <div class="table-responsive">
					<div class="container">

                    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Product Name:</strong>
                {{ $product->product_name }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Product Code:</strong>
                {{ $product->product_code }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Unit:</strong>
                    {{ $product->unit }}
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Bin:</strong>
                        {{ $product->bin }}
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="form-group">
                            <strong>Category:</strong>
                            {{ $product->category }}
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-12">
                            <div class="form-group">
                                <strong>Description:</strong>
                                {{ $product->description }}
                            </div>
                        </div>
    </div>

					</div>
                </div>
            </div>
        </div>
	</div>
</div>

@endsection