routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::resource('bins','BinController');
Route::resource('category','CategoryController');
Route::resource('unit','UnitController');
Route::resource('product','ProductController');
Route::resource('customer','CustomerController');
Route::resource('warehouse','WarehouseController');
Route::resource('role','RoleController');
Route::resource('user','UsersController');
Route::resource('report','ReportController');
Route::resource('report','UserrportController');


Route::get('dashboard', function () {
        return view('/dashboard');
    });

    Route::get('userreport', function () {
        return view('/userreport');
    });

app/Customer.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Customer extends Model
{
    protected $fillable = [
        'customer_group', 'name','company_name','email','phone_number','tax_no','address','city','state','postal_code','country','description','user_id',
    ];
}

app/Http/Controllers/CustomerController.php
<?php

namespace App\Http\Controllers;

use App\Customer;
use Illuminate\Http\Request;
use App\User;

class CustomerController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $customer = Customer::latest()->paginate(5);
  
        return view('customer.index',compact('customer'))
            ->with('i', (request()->input('page', 1) - 1) * 5);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $user = User::all();
        return view('customer.create',compact('user'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'customer_group' => 'required',
            'name' => 'required',
            'address' => 'required',
            'city' => 'required',
        ]);
  
        Customer::create($request->all());
   
        return redirect()->route('customer.index')
                        ->with('success','Customer created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Customer  $customer
     * @return \Illuminate\Http\Response
     */
    public function show(Customer $customer)
    {
        return view('customer.show',compact('customer'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Customer  $customer
     * @return \Illuminate\Http\Response
     */
    public function edit(Customer $customer)
    {
        return view('customer.edit',compact('customer'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Customer  $customer
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Customer $customer)
    {
        $request->validate([
            'customer_group' => 'required',
            'name' => 'required',
            'address' => 'required',
            'city' => 'required',
        ]);
  
        $customer->update($request->all());
  
        return redirect()->route('customer.index')
                        ->with('success','Customer updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Customer  $customer
     * @return \Illuminate\Http\Response
     */
    public function destroy(Customer $customer)
    {
        $customer->delete();
  
        return redirect()->route('customer.index')
                        ->with('success','Customer deleted successfully');
    }
}

resources/views/customer/create.blade.php
@extends('layouts.master')
 
@section('content')
<!-- content -->
<div id="content" class="app-content" role="main">
  <div class="app-content-body "> 
    <div class="bg-light lter b-b wrapper-md">
      <h1 class="m-n font-thin h3">Add New Customer</h1>
    </div>

    @if ($errors->any())
    <div class="alert alert-danger">
        <strong>Whoops!</strong> There were some problems with your input.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

    <div class="wrapper-md">
      <div class="panel panel-default">
      <div class="panel-heading btnbck">
            <a class="btn btn-success" href="{{ route('customer.index') }}"> Back</a>
          </div>
        <div class="table-responsive">
          <div class="container">
          <form action="{{ route('customer.store') }}" method="POST">
    @csrf
    <div class="row">
        <div class="col-xs-10 col-sm-10 col-md-6">
            <div class="form-group">
                <strong>Customer Group *</strong>
                <select name="customer_group" class="form-control">
                <option value="General">General</option>
                <option value="Distributer">Distributer</option>
                <option value="Reseller">Reseller</option>
                </select>
            </div>
        </div>
        <div class="col-xs-10 col-sm-10 col-md-6">
            <div class="form-group">
                <strong>Customer Name</strong>
                <input type="text" name="name" class="form-control" placeholder="Customer Name">
            </div>
        </div>

        <div class="col-xs-10 col-sm-10 col-md-6">
            <div class="form-group">
                <strong>Company Name</strong>
                <input type="text" name="company_name" class="form-control" placeholder="Company Name">
            </div>
        </div>
        <div class="col-xs-10 col-sm-10 col-md-6">
            <div class="form-group">
                <strong>Email</strong>
                <input type="email" name="email" class="form-control" placeholder="Enter Your Email">
                
                
            </div>
        </div>
        <div class="col-xs-10 col-sm-10 col-md-6">
            <div class="form-group">
                <strong>Phone Number *</strong>
                <input type="text" name="phone_number" class="form-control" placeholder="Enter Your Phone Number">
                
               
            </div>
        </div>
        <div class="col-xs-10 col-sm-10 col-md-6">
            <div class="form-group">
                <strong>Tax Number</strong>
                <input type="text" name="tax_no" class="form-control" placeholder="Enter Your tax Number">
                
               
            </div>
        </div>
        
        <div class="col-xs-10 col-sm-10 col-md-6">
            <div class="form-group">
                <strong>Address *</strong>
                <input type="text" name="address" class="form-control" placeholder="Enter Your Address">
                
               
            </div>
        </div>
        <div class="col-xs-10 col-sm-10 col-md-6">
            <div class="form-group">
                <strong>City *</strong>
                <input type="text" name="city" class="form-control" placeholder="Enter Your City">
                
               
            </div>
        </div>
        <div class="col-xs-10 col-sm-10 col-md-6">
            <div class="form-group">
                <strong>State</strong>
                <input type="text" name="state" class="form-control" placeholder="Enter Your State">
                
               
            </div>
        </div>
        <div class="col-xs-10 col-sm-10 col-md-6">
            <div class="form-group">
                <strong>Country</strong>
                <input type="text" name="country" class="form-control" placeholder="Enter Your Country">
                
               
            </div>
        </div>
        <div class="col-xs-10 col-sm-10 col-md-6">
            <div class="form-group">
                <strong>ZipCode</strong>
                <input type="text" name="postal_code" class="form-control" placeholder="Enter Your Zipcode">
                
               
            </div>
        </div>

        <div class="col-xs-6 col-sm-6 col-md-6">
            <div class="form-group">
                <strong>User:</strong>
                <select name="user_id" class="form-control">
                @foreach ($user as $val)
                    <option value="{{$val->id}}">{{$val->username}}</option>
                    @endforeach
                </select>
            </div>
        </div>

        <div class="col-xs-10 col-sm-10 col-md-6">
            <div class="form-group">
                <strong>description:</strong>
                <textarea class="form-control" style="height:150px" name="description" placeholder="description"></textarea>
            </div>
        </div>
        <div class="col-xs-10 col-sm-10 col-md-6 text-center btnsub">
                <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </div>
   
</form>
            </div>
          </div>
        </div>
          
      </div>
  </div>
</div>
</div>
</div>
@endsection

resources/views/customer/edit.blade.php
@extends('layouts.master')
   
@section('content')
<div id="content" class="app-content" role="main">
  <div class="app-content-body ">
    <div class="bg-light lter b-b wrapper-md">
      <h1 class="m-n font-thin h3">Edit Customer</h1>
    </div>
    @if ($errors->any())
    <div class="alert alert-danger">
        <strong>Whoops!</strong> There were some problems with your input.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

    <div class="wrapper-md">
      <div class="panel panel-default">
      <div class="panel-heading btnbck">
            <a class="btn btn-success" href="{{ route('customer.index') }}"> Back</a>
          </div>
        <div class="table-responsive">
          <div class="container">
          <form action="{{ route('customer.update',$customer->id) }}" method="POST">
        @csrf
        @method('PUT')
   
        <div class="row">
            <div class="col-xs-10 col-sm-10 col-md-6">
                <div class="form-group">
                    <strong>Customer Group *</strong>
                    <select name="customer_group" class="form-control">
    <option value="General">General</option>
    <option value="Distributer">Distributer</option>
    <option value="Reseller">Reseller</option>
                    </select>
                    
                </div>
            </div>
            <div class="col-xs-10 col-sm-10 col-md-6">
                <div class="form-group">
                    <strong>Customer Name</strong>
                <input type="text" name="name" class="form-control" value="{{$customer->name}}">
                </div>
            </div>
    
            <div class="col-xs-10 col-sm-10 col-md-6">
                <div class="form-group">
                    <strong>Company Name</strong>
                    <input type="text" name="company_name" class="form-control" value="{{$customer->company_name}}">
                </div>
            </div>
            <div class="col-xs-10 col-sm-10 col-md-6">
                <div class="form-group">
                    <strong>Email</strong>
                    <input type="email" name="email" class="form-control" value="{{$customer->email}}">
                    
                    
                </div>
            </div>
            <div class="col-xs-10 col-sm-10 col-md-6">
                <div class="form-group">
                    <strong>Phone Number *</strong>
                    <input type="text" name="phone_number" class="form-control" value="{{$customer->phone_number}}">
                    
                   
                </div>
            </div>
            <div class="col-xs-10 col-sm-10 col-md-6">
                <div class="form-group">
                    <strong>Tax Number</strong>
                    <input type="text" name="tax_no" class="form-control" value="{{$customer->tax_no}}">
                    
                   
                </div>
            </div>
            
            <div class="col-xs-10 col-sm-10 col-md-6">
                <div class="form-group">
                    <strong>Address *</strong>
                    <input type="text" name="address" class="form-control" value="{{$customer->address}}">
                    
                   
                </div>
            </div>
            <div class="col-xs-10 col-sm-10 col-md-6">
                <div class="form-group">
                    <strong>City *</strong>
                    <input type="text" name="city" class="form-control" value="{{$customer->city}}">
                    
                   
                </div>
            </div>
            <div class="col-xs-10 col-sm-10 col-md-6">
                <div class="form-group">
                    <strong>State</strong>
                    <input type="text" name="state" class="form-control" value="{{$customer->state}}">
                    
                   
                </div>
            </div>
            <div class="col-xs-10 col-sm-10 col-md-6">
                <div class="form-group">
                    <strong>Country</strong>
                    <input type="text" name="country" class="form-control" value="{{$customer->country}}">
                    
                   
                </div>
            </div>
            <div class="col-xs-10 col-sm-10 col-md-6">
                <div class="form-group">
                    <strong>ZipCode</strong>
                    <input type="text" name="postal_code" class="form-control" value="{{$customer->postal_code}}">
                    
                   
                </div>
            </div>
    
            <div class="col-xs-10 col-sm-10 col-md-6">
                <div class="form-group">
                    <strong>description:</strong>
                    <textarea class="form-control" style="height:150px" name="description">{{$customer->description}}</textarea>
                </div>
            </div>
            <div class="col-xs-10 col-sm-10 col-md-6 text-center btnsub">
                    <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>
           
   
    </form>
    </div>
    </div>
    </div>
   

  </div>
  </div>
</div>
</div>
</div>
  <!-- /content -->

      
@endsection























   

resources/views/customer/index.blade.php
@extends('layouts.master')
 
@section('content')
<!-- content -->
<div id="content" class="app-content" role="main">
  <div class="app-content-body ">
    <div class="bg-light lter b-b wrapper-md">
      <h1 class="m-n font-thin h3">Customer List</h1>
    </div>
    <div class="wrapper-md">
      <div class="panel panel-default">
        <div class="panel-heading">
          <a class="btn btn-success" href="{{ route('customer.create') }}"> Create New Customer</a>
        </div>
      <div class="table-responsive">
        <table ui-jq="dataTable" id="example" ui-options="{
          sAjaxSource: 'api/datatable.json',
          aoColumns: [
            { mData: 'engine' },
            { mData: 'browser' },
            { mData: 'platform' },
            { mData: 'version' },
            { mData: 'grade' }
          ]
        }" class="table table-striped table-bordered b-t b-b">
          <thead>
            <tr>
            <th>No</th>
            <th>Customer Group</th>
            <th>Name</th>
            <th>Company Name</th>
            <th>Email</th>
            <th>Phone No</th>
            <th width="280px">Action</th>
            </tr>
          </thead>
          <tbody>
          @foreach ($customer as $value)
              <tr>
              <td>{{ ++$i }}</td>
            <td>{{ $value->customer_group }}</td>
            <td>{{ $value->name }}</td>
            <td>{{ $value->company_name }}</td>
            <td>{{ $value->email }}</td>
            <td>{{ $value->phone_number }}</td>
           
            <td>
                <form action="{{ route('customer.destroy', $value->id) }}" method="POST">
   
                    <a class="btn btn-info" href="{{ route('customer.show',$value->id) }}">Show</a>
    
                    <a class="btn btn-primary" href="{{ route('customer.edit',$value->id) }}">Edit</a>
   
                    @csrf
                    @method('DELETE')
      
                    <button type="submit" class="btn btn-danger">Delete</button>
                </form>
            </td>
              </tr>
            @endforeach                  
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
</div>
  <!-- /content -->

      
@endsection

resources/views/customer/show.blade.php
@extends('layouts.master')
@section('content')

<!-- content -->
<div id="content" class="app-content" role="main">
  <div class="app-content-body ">
    <div class="bg-light lter b-b wrapper-md">
      <h1 class="m-n font-thin h3">Show Customer</h1>
    </div>
    <div class="wrapper-md">
      <div class="panel panel-default">
         <div class="table-responsive">
          <div class="container">
          <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
            <i class='fas fa-user-friends'></i>
                <strong>Customer Group:</strong>
                {{ $customer->customer_group }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
            <i class='fas fa-user'></i>
                <strong>Customer Name:</strong>
                {{ $customer->name }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                <i class='far fa-building'></i>
                <strong>Company Name:</strong>
                    {{ $customer->company_name }}
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                    <i class='fas fa-envelope'></i>
                        <strong>Email:</strong>
                        {{ $customer->email }}
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="form-group">
                        
                        <i class='fas fa-phone'></i>
                        <strong>Phone Number:</strong>
                            {{ $customer->phone_number }}
                        </div>
                    </div>

                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="form-group">
                        <i class='fas fa-print'></i>
                            <strong>Tax Number:</strong>
                            {{ $customer->tax_no }}
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="form-group">
                        <i class='fas fa-address-card'></i>
                            <strong>Address:</strong>
                            {{ $customer->address }}
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="form-group">
                        <i class='fas fa-city'></i>
                            <strong>City:</strong>
                            {{ $customer->city }}
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="form-group">
                        <i class='fas fa-city'></i>
                            <strong>state:</strong>
                            {{ $customer->state }}
                        </div>
                    </div>

                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="form-group">
                        <i class='far fa-file'></i>
                            <strong>Zipcode:</strong>
                            {{ $customer->postal_code }}
                        </div>
                    </div>

                    
                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="form-group">
                        <i class='fas fa-globe'></i>
                            <strong>Country:</strong>
                            {{ $customer->country }}
                        </div>
                    </div>

                    <div class="col-xs-12 col-sm-12 col-md-12">
                            <div class="form-group">
                            <i class='fas fa-file-alt'></i>
                                <strong>Description:</strong>
                                {{ $customer->description }}
                            </div>
                        </div>
    </div>
      @if ($errors->any())
        <div class="alert alert-danger">
          <strong>Whoops!</strong> There were some problems with your input.<br><br>
          <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
          </ul>
    <div>
@endif
            


                            
        
    </div>
  </div>
</div>



	</div>
  </div>
  <!-- /content -->

      
@endsection